### ISSUE TITLE
Pip failed error

### ISSUE THREAD

**Issue by baidefeng** [KennthShang/PhaGCN#13]
When i run "conda env create -f environment.yaml -n phagcn", an "Pip failed" error occurred as below, i upgraded the pip but same error occurred, do you have ideas how to fix it? Thanks.

Channels:
 - pytorch
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: | By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/data5/baidefeng/miniconda3/envs/phagcn/bin/python', '-m', 'pip', 'install', '-U', '-r', '/data5/baidefeng/virus6/temp/PhaGCN/condaenv.zyqxs9c3.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 269, in run
    session = self.get_default_session(options)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 77, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 87, in _build_session
    session = PipSession(
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/network/session.py", line 275, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    linux_distribution = distro.linux_distribution()  # type: ignore
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 127.
Traceback (most recent call last):
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 71, in main
    return command.main(cmd_args)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 104, in main
    return self._main(args)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 221, in _main
    self.handle_pip_version_check(options)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 143, in handle_pip_version_check
    session = self._build_session(
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 87, in _build_session
    session = PipSession(
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/network/session.py", line 275, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    linux_distribution = distro.linux_distribution()  # type: ignore
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/data5/baidefeng/miniconda3/envs/phagcn/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 127.

failed

CondaEnvException: Pip failed

**Comment by KennthShang** [comment]
Hi there, 

Please note that:
![image](https://github.com/user-attachments/assets/70a7cc89-e58c-45e7-9d92-df736a1a9cc4)

Best,
Jiayu
